### ISSUE TITLE
Add remaining features for 3.17 support

### ISSUE THREAD

**Issue by tombh** [openlawlibrary/pygls#346]
Thanks to @alcarney we've identified the remaining features we need to add for complete LSP 3.17 compliance.

New methods:
- [x] Add support for type hierarchies. #370
- [x] Add support for inline values. #369 
- [x] Add support for inlay hints. #342 
- [x] Add support for workspace symbol resolve request. #362 
- [x] Add support for diagnostic pull model. #360 

Other:
- [x] Add support for notebook documents. #356 
   See also, https://github.com/openlawlibrary/pygls/issues/311 
- [x] Add support to negotiate the position encoding. 
   Some minor discussion here https://github.com/openlawlibrary/pygls/pull/304#issuecomment-1583811242
